import sys
import codecs
import random
pet = '0'
hat = '0'
skin = '0'
color = '0'
name = '0'
answer = input("Enter 1 to make your apperance. Enter 2 to make a random apperance. Enter 3 To Get A Costume. ")
if answer == '1':
	print(" ")
	print("Enter a name between 1 and 10 letters.")
	name = input("")
	print(" ")
	print("Enter number To pick your color")
	print("	0. Red")
	print("	1. Blue")
	print("	2. Green")
	print("	3. Pink")
	print("	4. Orange")
	print("	5. Yellow")
	print("	6. Black")
	print("	7. White")
	print("	8. Purple")
	print("	9. Brown")
	print("	10. Cyan")
	print("	11. Lime")
	print("	12. Fortegreen")
	color = input("")
	print(" ")
	print("Enter number To pick your pet")
	print("	0. None")
	print("	1. Alien")
	print("	2. Crewmate")
	print("	3. Doggy")
	print("	4. Stickmin")
	print("	5. Hamster")
	print("	6. Robot")
	print("	7. UFO")
	print("	8. Ellie")
	print("	9. Squig")
	print("	10. Bedcrab")
	print("	11. Glitch")
	print(" ")
	pet = input("")
	print(" ")
	print("Enter number to pick your skin")
	print("	0. None")
	print("	1. Astro")
	print("	2. Capt")
	print("	3. Mech")
	print("	4. Millitary")
	print("	5. Police")
	print("	6. Science")
	print("	7. SuitB")
	print("	8. SuitW")
	print("	9. Wall")
	print("	10. Hazmat")
	print("	11. Security")
	print("	12. Tarmac")
	print("	13. Miner")
	print("	13. Miner")
	print("	14. Winter")
	print("	15. Archae")
	print(" ")
	skin = input("")
	print(" ")
	print("File Size Too Big. Go To https://wiki.weewoo.net/wiki/Enums#Hat For Hat Id's. Enter A Id Between 1 and 94.")
	hat = input("")
	print(" ")
	print("Close Among Us If It Is Open And Open/Reopen Among Us. Your Apperance Has Been Made.")
	with open("C:\\Users\\harpe\\AppData\\LocalLow\\Innersloth\\Among Us\\playerPrefs", "w") as f:
		f.write(name +",1," + color + ",1,False,False,False,0,False,False," + hat + ",0,0,0,0," + skin + "," + pet + ",False,0,False,0,1,,1,1,2000,3/14/9999 10:49:29 PM,1")
	quit(1)
if answer == '2':
	pet = random.randint(1, 11)
	pet = str(pet)
	skin = random.randint(1, 15)
	skin = str(skin)
	hat = random.randint(1, 94)
	hat = str(hat)
	color = random.randint(0, 12)
	color = str(color)
	with open("C:\\Users\\harpe\\AppData\\LocalLow\\Innersloth\\Among Us\\playerPrefs", "w") as f:
		f.write(name +",1," + color + ",1,False,False,False,0,False,False," + hat + ",0,0,0,0," + skin + "," + pet + ",False,0,False,0,1,,1,1,2000,3/14/9999 10:49:29 PM,1")
	print(" ")
	print("Close Among Us If It Is Open And Reopen/Open Among Us. Your Apperance Has Been Made.")
	quit(1)
if answer == '3':
	print("")
